//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteNET.ServicioWebSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServicioWebSOAP.WSOperaciones")]
    public interface WSOperaciones {
        
        // CODEGEN: Generating message contract since element name usuario from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/LoginRequest", ReplyAction="http://ws/WSOperaciones/LoginResponse")]
        ClienteNET.ServicioWebSOAP.LoginResponse Login(ClienteNET.ServicioWebSOAP.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/LoginRequest", ReplyAction="http://ws/WSOperaciones/LoginResponse")]
        System.Threading.Tasks.Task<ClienteNET.ServicioWebSOAP.LoginResponse> LoginAsync(ClienteNET.ServicioWebSOAP.LoginRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/ProcesarPagoRequest", ReplyAction="http://ws/WSOperaciones/ProcesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteNET.ServicioWebSOAP.ProcesarPagoResponse ProcesarPago(ClienteNET.ServicioWebSOAP.ProcesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/ProcesarPagoRequest", ReplyAction="http://ws/WSOperaciones/ProcesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteNET.ServicioWebSOAP.ProcesarPagoResponse> ProcesarPagoAsync(ClienteNET.ServicioWebSOAP.ProcesarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ws/", Order=0)]
        public ClienteNET.ServicioWebSOAP.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClienteNET.ServicioWebSOAP.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ws/", Order=0)]
        public ClienteNET.ServicioWebSOAP.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClienteNET.ServicioWebSOAP.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPago", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ProcesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pago;
        
        public ProcesarPagoRequest() {
        }
        
        public ProcesarPagoRequest(int total, int pago) {
            this.total = total;
            this.pago = pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPagoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ProcesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public ProcesarPagoResponse() {
        }
        
        public ProcesarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOperacionesChannel : ClienteNET.ServicioWebSOAP.WSOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOperacionesClient : System.ServiceModel.ClientBase<ClienteNET.ServicioWebSOAP.WSOperaciones>, ClienteNET.ServicioWebSOAP.WSOperaciones {
        
        public WSOperacionesClient() {
        }
        
        public WSOperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNET.ServicioWebSOAP.LoginResponse ClienteNET.ServicioWebSOAP.WSOperaciones.Login(ClienteNET.ServicioWebSOAP.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string usuario, string contrasena) {
            ClienteNET.ServicioWebSOAP.LoginRequest inValue = new ClienteNET.ServicioWebSOAP.LoginRequest();
            inValue.Body = new ClienteNET.ServicioWebSOAP.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            ClienteNET.ServicioWebSOAP.LoginResponse retVal = ((ClienteNET.ServicioWebSOAP.WSOperaciones)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNET.ServicioWebSOAP.LoginResponse> ClienteNET.ServicioWebSOAP.WSOperaciones.LoginAsync(ClienteNET.ServicioWebSOAP.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNET.ServicioWebSOAP.LoginResponse> LoginAsync(string usuario, string contrasena) {
            ClienteNET.ServicioWebSOAP.LoginRequest inValue = new ClienteNET.ServicioWebSOAP.LoginRequest();
            inValue.Body = new ClienteNET.ServicioWebSOAP.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((ClienteNET.ServicioWebSOAP.WSOperaciones)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNET.ServicioWebSOAP.ProcesarPagoResponse ClienteNET.ServicioWebSOAP.WSOperaciones.ProcesarPago(ClienteNET.ServicioWebSOAP.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPago(request);
        }
        
        public int ProcesarPago(int total, int pago) {
            ClienteNET.ServicioWebSOAP.ProcesarPagoRequest inValue = new ClienteNET.ServicioWebSOAP.ProcesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            ClienteNET.ServicioWebSOAP.ProcesarPagoResponse retVal = ((ClienteNET.ServicioWebSOAP.WSOperaciones)(this)).ProcesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNET.ServicioWebSOAP.ProcesarPagoResponse> ClienteNET.ServicioWebSOAP.WSOperaciones.ProcesarPagoAsync(ClienteNET.ServicioWebSOAP.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNET.ServicioWebSOAP.ProcesarPagoResponse> ProcesarPagoAsync(int total, int pago) {
            ClienteNET.ServicioWebSOAP.ProcesarPagoRequest inValue = new ClienteNET.ServicioWebSOAP.ProcesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            return ((ClienteNET.ServicioWebSOAP.WSOperaciones)(this)).ProcesarPagoAsync(inValue);
        }
    }
}
